# Generated by Django 3.0.6 on 2020-06-06 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0003_hotels_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='things',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('things', models.TextField()),
                ('pics', models.ImageField(default='', upload_to='pics')),
            ],
        ),
    ]
