# Generated by Django 3.0.6 on 2020-06-06 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0004_things'),
    ]

    operations = [
        migrations.AddField(
            model_name='things',
            name='desc',
            field=models.TextField(default=''),
        ),
    ]
