# Generated by Django 3.0.6 on 2020-06-09 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0005_things_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='restaurants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('restaurant', models.CharField(max_length=400)),
                ('famous', models.TextField()),
                ('start', models.CharField(max_length=50)),
                ('end', models.CharField(max_length=50)),
                ('ratings', models.IntegerField()),
                ('phone', models.IntegerField()),
                ('price', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
            ],
        ),
    ]
