# Generated by Django 3.0.6 on 2020-06-09 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0008_flights'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flights',
            name='noof',
        ),
        migrations.AddField(
            model_name='flights',
            name='hours',
            field=models.CharField(default='06', max_length=200),
        ),
        migrations.AddField(
            model_name='flights',
            name='nameof',
            field=models.CharField(default='Indian Internationals', max_length=200),
        ),
        migrations.AlterField(
            model_name='flights',
            name='From',
            field=models.CharField(default='New Delhi', max_length=200),
        ),
        migrations.AlterField(
            model_name='flights',
            name='To',
            field=models.CharField(default='Canada', max_length=200),
        ),
        migrations.AlterField(
            model_name='flights',
            name='name',
            field=models.CharField(default='NOT FOUND', max_length=200),
        ),
        migrations.AlterField(
            model_name='flights',
            name='price',
            field=models.CharField(default='Rs.30000.00', max_length=400),
        ),
    ]
