# Generated by Django 3.0.6 on 2020-06-09 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('account', models.CharField(max_length=200)),
                ('password', models.IntegerField()),
                ('email', models.CharField(max_length=200)),
            ],
        ),
    ]
